# Generated by Django 4.2.3 on 2023-08-02 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_suser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('PUMA', 'PUMA'), ('ADIDAS', 'ADIDAS'), ('BATA', 'BATA'), ('CAMPUS', 'CAMPUS')], max_length=100)),
                ('size', models.CharField(choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=100)),
                ('pic', models.ImageField(upload_to='profile_pic/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.suser')),
            ],
        ),
    ]
